[project]
name = 'timetablechain'
authors = []
description = 'Decentralized teaching slot marketplace on Stacks'
telemetry = false
requirements = []

[contracts.timetablechain]
path = 'contracts/timetablechain.clar'
clarity_version = 3
epoch = '3.0'

[contracts.slot-marketplace]
path = 'contracts/slot-marketplace.clar'
clarity_version = 3
epoch = '3.0'

[contracts.teacher-reputation]
path = 'contracts/teacher-reputation.clar'
clarity_version = 3
epoch = '3.0'

[contracts.attendance-tracker]
path = 'contracts/attendance-tracker.clar'
clarity_version = 3
epoch = '3.0'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
